### ISSUE TITLE
Change gebug init  application name title

### ISSUE THREAD

**Issue by lucas-gio** [moshebe/gebug#107]
**Problem**
in gebug init, the first title say: Application Name, but here wants a docker image name instead.
I enter this in the init process:
Application Name: goRest
[...]  // ...and the others fields
And i give an unexpected error:
$ gebug start
ERROR: Service 'gebug-goRest' contains uppercase characters which are not valid as part of an image name. Either use a lowercase service name or use the `image` field to set a custom name for the service image.

**Solution**
To change Application Name to Docker image name (or similar)

**Comment by moshebe** [comment]
Thanks for the detailed issue @lucas-gio!
You are right, we should handle those name as well.
But, I'm not sure if exposing them as docker image name will be the correct solution as it's only an implementation detail and should not bother as user (also, it will be prefixed and with 'gebug-' so it might be also misleading)

I think we can sanitize the input (e.g. convert the Upper case letters to lower case) for the image name but keep the application/service name as the user request. WDYT?

**Comment by lucas-gio** [comment]
I think that your solution is better. Thanks for your response.

Greetings!!
