### ISSUE TITLE
SIGTERM handle

### ISSUE THREAD

**Issue by saiks24** [moshebe/gebug#12]
Now, when receiving signal 15 (SIGTERM) (cmd+c in console) from the user, the program crashes with an error

`2020-07-21T19:45:07.909+0300	FATAL	cmd/init.go:32	Failed to initialize project	{"error": "^C"}
github.com/moshebe/gebug/cmd.glob..func3
	/Users/miksmolin/gebug/cmd/init.go:32
github.com/spf13/cobra.(*Command).execute
	/Users/miksmolin/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846
github.com/spf13/cobra.(*Command).ExecuteC
	/Users/miksmolin/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
	/Users/miksmolin/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/moshebe/gebug/cmd.Execute
	/Users/miksmolin/gebug/cmd/root.go:38
main.main
	/Users/miksmolin/gebug/main.go:6
runtime.main
	/Users/miksmolin/homebrew/Cellar/go@1.13/1.13.10_1/libexec/src/runtime/proc.go:203`

Would be great to add SIGTERM handling for graceful shutdown.

**Comment by moshebe** [comment]
Hi @saiks24,
Thanks for taking the time and opening this issue.
Can you please describe the expected behavior in your opinion?
I guess if you stopped during the init process, an error should be printed and the application should exit.
But what does the graceful shutdown means here? handling the output stack print or something more than that?

**Comment by saiks24** [comment]
Hi. Thanks for reading my issue.
 I think there might be a more user-friendly interrupt message when a SIGTERM signal is received. So that the user understands that the error is in the interrupt signal. 
This is not obvious in the current error handler.

**Comment by saiks24** [comment]
Maybe a message like: gebug {Command_name} was interrupted by the user. 
{Command_name} was failed.

**Comment by moshebe** [comment]
Cool, thanks. I'm on it.

**Comment by saiks24** [comment]
Thank. I will definitely make a pull request in the near time.

**Comment by moshebe** [comment]
Sorry, did not understand you planned to do it on your own. I've already made a little fix (fortunately, promptui already handles SIGTERM and return a custom error for this one so it was actually one-line change).

Please take a look and tell me what do you think:
https://github.com/moshebe/gebug/pull/13

**Comment by saiks24** [comment]
I looked at the pull request https://github.com/moshebe/gebug/pull/13. Great, I think this is what we need.
Thank you.
