### ISSUE TITLE
Create release and make the version command receive the current version automatically

### ISSUE THREAD

**Issue by UrielShimony** [moshebe/gebug#23]
Currently, there are no releases. and the version is hard-coded v0.0.1. There should be an automatic way to get the release name.

**Comment by moshebe** [comment]
Thanks @UrielShimony, I'll fix it soon.
Let me know if you want to work on this feature.

**Comment by moshebe** [comment]
Added in latest version.
Using the official installation will result with the release tag (e.g. `1.0.2`)
For locally built versions we will use the following format (used by git describe): `v1.1.2-0-gc9c8407`

Thanks for opening the issue!
