### ISSUE TITLE
Support environment varialbes

### ISSUE THREAD

**Issue by rabanian** [moshebe/gebug#5]
Currently It seems like the only option to add env vars would be to edit the .gebug/Dockerfile.. Would be great if there's an option to pass env vars without much manual work.

**Comment by moshebe** [comment]
First, thanks for your feedback @rabanian. I think it's a good point!

You are right, currently, the solution can be modifying directly the `Dockerfile` or the `docker-compose.yml` under `.gebug` directory. Just pay attention to the `gebug start` override your changes unless you use `--skip-generate`.

I think a good option to add environment variables would be via the interactive `init` command, pretty similar to the add expose ports option.
And maybe we can add a `gebug add env <name> <value>` command.
WDYT?

Please let me know if you want to work on this feature, and of course, I'm available to help if needed.

**Comment by moshebe** [comment]
Hi @rabanian, 
The feature you wanted is now available via the `init` command, enjoy it!

**Comment by rabanian** [comment]
That's great, thanks!
