### ISSUE TITLE
Support remote hot-reload

### ISSUE THREAD

**Issue by talhof8** [moshebe/gebug#6]
Support hot-reload while the Docker container is running on a remote machine. Support rsync, scp, S3, git.

**Comment by moshebe** [comment]
Let me make sure I understand you correctly.
Do you want to work locally using an IDE and sync the source files automatically to the remote machine and run the Docker commands on it?
Sounds cool. 
I think it can be implemented using SSH for the command execution and `rsync` or one of the options you mentioned for the source files syncing.

WDYT?

Do you to work on this feature? I'd be happy to help you.

**Comment by talhof8** [comment]
Yup, you understand me correctly :)

I think `rsync` would be a ideal for syncing. In the future I might want to use some remote git repository or even s3 for storage, so I think it'd be nice if it's implemented in a modular way. The default syncing & storage method could be `local`, and so additional methods could be used if needed (`rsync` seems like a great start). 

I'm not currently working on this feature. Will do soon, probably. 

Thanks! :)

**Comment by moshebe** [comment]
Hi,
Please take a look on the blog post I published.
I think you can get your desired environment using Telepresence and Gebug the way I showed.

WDYT?

**Comment by talhof8** [comment]
Looking good. Closing issue.
