### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by gauravve** [moshebe/gebug#7]
getting the following error while running go get

```
go get -v github.com/moshebe/gebug

go: github.com/moshebe/gebug upgrade => v0.0.0-20200721074100-a66de0d5eca3
go get: github.com/moshebe/gebug@v0.0.0-20200721074100-a66de0d5eca3: parsing go.mod:
	module declares its path as: gebug
	        but was required as: github.com/moshebe/gebug

```

**Comment by moshebe** [comment]
Hi, as @InbarPerry mentioned, it looks like a go module name problem I'll review and merge his fix soon.
But, I think you run the `go get -v github.com/moshebe/gebug` command inside a go-mod project (which adds gebug as dependency to your project, but what you actually need is to install the utility on your machine)
Please try running the command  `go get -u github.com/moshebe/gebug` outside your project, in another directory that has no go.mod in it and let me know if it works for you.

**Comment by markvai** [comment]
Hi, i am trying to install with `go get -u github.com/moshebe/gebug` in a directory without .go.mod and get:
`unrecognized import path "gebug/cmd": import path does not begin with hostname`

**Comment by moshebe** [comment]
Hi @markvai, can you please try again? I just merged @InbarPerry fix.

**Comment by markvai** [comment]
@moshebe Thanks, it works now.

**Comment by moshebe** [comment]
Thank to @InbarPerry. 
@gauravve are you still facing the problem or can I close this issue?
