### ISSUE TITLE
Select an existing network to join

### ISSUE THREAD

**Issue by moshebe** [moshebe/gebug#9]
as requested by johnnMackk on r/golang:
"One question, is there a way to select the network that gebug can connects to? I am just thinking of a use case where I have a server that wants to speak to another service sql db for example".

I think the network can be set via the interactive init command or via dedicated `set network` command or something alike.

**Comment by InbarPerry** [comment]
maybe we can run `docker network list` to see which networks are available and let the user choose from that list (or create a custom one)

It will require some changes to osutil in order to get the output from the command to a variable instead of stdout

what do you think?

**Comment by moshebe** [comment]
It can nice, but I think we can start even with a smaller feature.
What about just getting the network name from the user (via the `init` command and/or a custom `add network` one) and put it as an external network in the docker-compose?
(see: https://docs.docker.com/compose/networking/#use-a-pre-existing-network)

We can then, as a separate feature, make some auto-complete and suggestion features like the one you mentioned.

WDYT?

**Comment by InbarPerry** [comment]
Sounds good. Let's start with the basics and i'll add it as an improvement for later.
